import { notFound } from "next/navigation";
import { PortalPageHeading } from "@/components/portal/page-heading";
import { BuyAgainButton } from "@/components/commerce/buy-again-button";
import { formatKobo } from "@/lib/money";
import { prisma } from "@/lib/prisma";
import { requireCustomer } from "@/server/auth/session";

export default async function AccountOrderDetailsPage({number}:{number:string}){const session=await requireCustomer();const order=await prisma.order.findFirst({where:{number,userId:session.user.id},include:{items:true,payments:{orderBy:{createdAt:"desc"}},shipments:{include:{events:{orderBy:{occurredAt:"desc"}}}},statusHistory:{orderBy:{createdAt:"desc"}}}});if(!order)notFound();return <><PortalPageHeading eyebrow="Order details" title={order.number} description={`Placed ${new Intl.DateTimeFormat("en-NG",{dateStyle:"long"}).format(order.createdAt)}`} action={<BuyAgainButton items={order.items.map(item=>({sku:item.sku,quantity:item.quantity}))}/>} /><div className="mt-7 grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><section className="rounded-[1.5rem] border border-mayera-line bg-mayera-paper p-6"><h2 className="font-serif text-2xl">Items</h2><div className="mt-5 divide-y divide-mayera-line">{order.items.map(item=><div key={item.id} className="flex justify-between gap-5 py-4"><div><p className="font-medium">{item.name}</p><p className="mt-1 text-xs text-mayera-espresso/48">{item.sku} · Quantity {item.quantity}</p></div><p className="text-sm font-medium">{formatKobo(item.totalKobo)}</p></div>)}</div><div className="mt-5 space-y-2 border-t border-mayera-line pt-5 text-sm"><Row label="Subtotal" value={formatKobo(order.subtotalKobo)}/><Row label="Delivery" value={formatKobo(order.shippingKobo)}/>{order.discountKobo?<Row label="Discount" value={`−${formatKobo(order.discountKobo)}`}/>:null}<Row label="Total" value={formatKobo(order.totalKobo)} strong/></div></section><div className="space-y-6"><Panel title="Delivery"><p>{order.shippingName}</p><p>{order.shippingLine1}</p>{order.shippingLine2?<p>{order.shippingLine2}</p>:null}<p>{order.shippingCity}, {order.shippingState}</p>{order.shipments[0]?.trackingCode?<p className="mt-4 font-medium">Tracking: {order.shipments[0].trackingCode}</p>:<p className="mt-4 text-mayera-espresso/48">Tracking appears here after dispatch.</p>}</Panel><Panel title="Status history">{order.statusHistory.map(entry=><div key={entry.id} className="border-b border-mayera-line py-3 last:border-0"><p className="font-medium">{entry.status.replaceAll("_"," ")}</p><p className="mt-1 text-xs text-mayera-espresso/48">{new Intl.DateTimeFormat("en-NG",{dateStyle:"medium",timeStyle:"short"}).format(entry.createdAt)}</p>{entry.note?<p className="mt-1 text-xs text-mayera-espresso/55">{entry.note}</p>:null}</div>)}</Panel></div></div></>}
function Row({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <div className={`flex justify-between ${strong?"pt-2 text-base font-semibold":"text-mayera-espresso/65"}`}><span>{label}</span><span>{value}</span></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-[1.5rem] border border-mayera-line bg-mayera-paper p-6 text-sm leading-7"><h2 className="mb-3 font-serif text-2xl">{title}</h2>{children}</section>}
