import Link from "next/link";
import { Container } from "@/components/ui/container";
import { ProductCard } from "@/components/commerce/product-card";
import { getJournalArticles, getStoreProducts } from "@/server/catalog/public";

export default async function SearchPage({ query }: { query: string }) {
  const term = query.trim().toLowerCase();
  const [products, articles] = await Promise.all([getStoreProducts(), getJournalArticles()]);
  const productMatches = term ? products.filter((product) => [product.name, product.subtitle, product.description, ...product.benefits, ...product.categories.map((category) => category.name)].join(" ").toLowerCase().includes(term)) : [];
  const articleMatches = term ? articles.filter((article) => [article.title, article.excerpt, article.category].join(" ").toLowerCase().includes(term)) : [];
  return <main>
    <section className="bg-mayera-cream py-14 sm:py-16"><Container><p className="text-xs font-semibold uppercase tracking-luxury text-mayera-olive">Search</p><h1 className="mt-4 font-serif text-5xl tracking-[-.04em]">Find your way through Mayéra.</h1><form className="mt-7 flex max-w-2xl gap-3"><label htmlFor="q" className="sr-only">Search products and Hair Journal</label><input id="q" name="q" defaultValue={query} required autoFocus placeholder="Search products, categories or journal…" className="min-h-12 min-w-0 flex-1 rounded-full border border-mayera-line bg-white px-5 text-sm outline-none focus:border-mayera-olive" /><button className="shrink-0 rounded-full bg-mayera-espresso px-5 text-sm text-white sm:px-6">Search</button></form></Container></section>
    <Container className="py-16 md:py-20">{term ? <><p className="text-sm text-mayera-espresso/55">{productMatches.length + articleMatches.length} result{productMatches.length + articleMatches.length === 1 ? "" : "s"} for “{query}”</p>{productMatches.length ? <section className="mt-8"><h2 className="font-serif text-3xl">Products</h2><div className="mt-6 grid gap-7 md:grid-cols-2 xl:grid-cols-4">{productMatches.map((product) => <ProductCard key={product.id} product={product} />)}</div></section> : null}{articleMatches.length ? <section className="mt-12"><h2 className="font-serif text-3xl">Hair Journal</h2><div className="mt-5 divide-y divide-mayera-line border-y border-mayera-line">{articleMatches.map((article) => <Link key={article.slug} href={`/hair-journal/${article.slug}`} className="block py-5"><p className="text-xs uppercase tracking-[.12em] text-mayera-olive">{article.category}</p><h3 className="mt-2 font-serif text-2xl">{article.title}</h3><p className="mt-2 text-sm text-mayera-espresso/55">{article.excerpt}</p></Link>)}</div></section> : null}{!productMatches.length && !articleMatches.length ? <div className="mt-8 rounded-[1.5rem] border border-dashed border-mayera-line p-10 text-center"><p className="font-serif text-3xl">No matches yet.</p><p className="mt-3 text-sm text-mayera-espresso/55">Try a product name, category, “scalp” or “ingredients”.</p></div> : null}</> : <div className="rounded-[1.5rem] border border-dashed border-mayera-line p-10 text-center"><p className="font-serif text-3xl">Search products and education.</p><p className="mt-3 text-sm text-mayera-espresso/55">Enter a word above to begin.</p></div>}</Container>
  </main>;
}
